[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ["-C", "link-args=-Tsrc/riscv.lds"]

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -M virt -no-reboot -nographic -serial mon:stdio -kernel"
